# -*- coding: utf-8 -*-
"""demo_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IhBJCCdzxiO-ogix3Md4n2gcwWvKOwKl
"""

import sqlite3

#question 1

conn = sqlite3.connect('demo_data.sqlite3')

curs = conn.cursor()

#computing values
Col1, Col2, Col3 = ('s', 'x', 'y')

curs.execute("DROP TABLE demo;")

curs.execute("""CREATE TABLE IF NOT EXISTS demo
    (id INTEGER PRIMARY KEY,
    Col1 TEXT,
    Col2 INTEGER,
    Col3 INTEGER);""")

curs.execute("""INSERT INTO demo
                (Col1, Col2, Col3) VALUES (?, ?, ?)""",
                (Col1, Col2, Col3))

conn.commit()

