# -*- coding: utf-8 -*-
"""Northwind.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16BN-VAZnoCQ3sk49fN18Kr1rsByefNe0
"""

import sqlite3

#PART 2

conn = sqlite3.connect('northwind_small.sqlite3')

curs = conn.cursor()

curs.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;").fetchall()

query = '''Select(UnitPrice) FROM Product ORDER BY (unitprice) DESC limit 10;'''
curs.execute(query).fetchall()

conn.commit()

#Part 3

curs.execute('SELECT sql FROM sqlite_master WHERE name="Product";').fetchall()

curs.execute('SELECT sql FROM sqlite_master WHERE name="Supplier";').fetchall()

query ='''SELECT Product.UnitPrice, Supplier.CompanyName
FROM Product
INNER JOIN Supplier ON
Product.Id = Supplier.Id
ORDER BY (unitprice) DESC limit 10;'''
curs.execute(query).fetchall()

conn.commit()

#Part 4

#A one to one relationship? An employee only work in one area
# MongoDB is a NoSQL meaning it isn't structured. These are usefull when storage price is big factor
#New SQL is all about merging the benefits of No SQL and SQL. An example of NO SQL is apache

