# -*- coding: utf-8 -*-
"""Krista Shepard U3S2M1 - Assignment 1 Part 3 - Intro to SQL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l1SvvPmH9fuPoPs4QjSAlsbJwE7uXkjq
"""

import pandas as pd
import sqlite3

"""### Loaded the data from the provided file buddymove_holidayiq.csv 
### I have 249 rows, 7 columns, and no missing values.
"""

buddy = pd.read_csv('https://raw.githubusercontent.com/KryssyCo/'
                    'DS-Unit-3-Sprint-2-SQL-and-Databases/master/'
                    'module1-introduction-to-sql/buddymove_holidayiq.csv')
print(buddy.shape)
buddy.head()

buddy.isnull().sum()

"""### Using the standard sqlite3 module:

- I opened a connection to a new (blank) database file buddymove_holidayiq.sqlite3
- Used df.to_sql (documentation) to insert the data into a new table review in the SQLite3 database
"""

# Establish a connection to a new database
conn = sqlite3.connect('buddymove)holidayiq.sqlite3')

#Inserted the data into a new table called "review" in the database
buddy.to_sql(name = 'review', con = conn)

"""### Counting how many rows I have now"""

# Create a cursor.
curs1 = conn.cursor()

# Write a query
query1 = 'SELECT COUNT(*) FROM review;'

# Execute the query
total_rows = curs1.execute(query1).fetchall()

# Print Answer
print(total_rows)

"""### How many users who reviewed at least 100 Nature in the category also reviewed at least 100 in the Shopping category?"""

#Create a cursor.
curs2 = conn.cursor()

#Write a query.
query2 = """
SELECT COUNT(*)
FROM review
WHERE Nature >= 100 AND Shopping >= 100;
"""

#Execute the query.
users = curs2.execute(query2).fetchall()

print(users)

"""### (Stretch) What are the average number of reviews for each category?"""

#Create a cursor.
curs3 = conn.cursor()

#Write a query.
query3 = """
SELECT AVG(Sports), AVG(Religious), AVG(Nature), AVG(Theatre),
AVG(Shopping), AVG(Picnic)
FROM review;"""

#Execute the query()
avg_reviews_column = curs3.execute(query3).fetchall()

print(avg_reviews_column)