INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (1, 'Aliquid iste optio reiciendi', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (2, 'Optio dolorem ex a', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (3, 'Minus c', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (4, 'Sit ut repr', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (5, 'At id recusandae expl', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (6, 'Non nobis et of', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (7, 'Perferendis', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (8, 'Accusantium amet quidem eve', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (9, 'Sed nostrum inventore error m', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (10, 'Harum repellendus omnis od', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (11, 'Itaque ut commodi,', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (12, 'Molestiae quis', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (13, 'Ali', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (14, 'Tempora quod optio possimus il', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (15, 'Sed itaque beatae pari', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (16, 'Quam dolor', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (17, 'Molestias expedita', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (18, 'Lauda', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (19, 'Incidunt sint perferen', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (20, 'Laboriosa', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (21, 'Dolore esse nesciunt fugit com', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (22, 'Dolorum nam reic', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (23, 'Repellat ad numquam volu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (24, 'Facere enim velit eligend', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (25, 'Sed ratione quis rep', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (26, 'Doloribus neque', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (27, 'Ab voluptas se', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (28, 'Molestias m', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (29, 'In pariatur corpori', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (30, 'Possimus ad dignissimos vel, a', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (31, 'At minus accusa', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (32, 'Ad necess', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (33, 'Expedita c', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (34, 'Voluptates sunt voluptas volu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (35, 'Autem mollitia fuga lauda', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (36, 'Sint quibusdam ob', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (37, 'Rerum et o', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (38, 'Doloribus dolore r', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (39, 'Eaque su', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (40, 'Vel molestias numqua', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (41, 'Iste assumenda repellat q', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (42, 'Animi labo', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (43, 'Eum culpa eaque ea omn', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (44, 'Harum provident vel quam', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (45, 'Aspe', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (46, 'Nisi nequ', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (47, 'Quod tempora', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (48, 'Porro aliq', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (49, 'Quas', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (50, 'Magnam eligendi quia animi', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (51, 'Officiis se', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (52, 'Id assumend', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (53, 'Voluptatibus fu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (54, 'Odit rat', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (55, 'Debit', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (56, 'Cum aut quas repudia', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (57, 'Deleniti qui quae quidem', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (58, 'Adipisci voluptas', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (59, 'Debitis sit ratione eos nam', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (60, 'Esse illo molestias archi', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (61, 'Sunt at itaque voluptatum d', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (62, 'Est totam', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (63, 'Reprehenderit commodi eius', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (64, 'Debit', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (65, 'Soluta dol', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (66, 'Vel nesc', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (67, 'Ratione quia ali', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (68, 'Rerum recusandae minima', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (69, 'Totam natus eius fugiat volu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (70, 'Perferendis commodi null', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (71, 'Laudantiu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (72, 'Voluptat', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (73, 'Incidunt nesciun', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (74, 'Illum amet vero', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (75, 'Suscipit exercitationem re', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (76, 'Quas enim error maxime nisi m', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (77, 'Labore qu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (78, 'Repudiandae deleniti unde', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (79, 'Ut do', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (80, 'Quaerat esse labore q', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (81, 'Quidem aliq', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (82, 'Aperiam vitae eos dolor sed', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (83, 'Minus nobis porro', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (84, 'In similique', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (85, 'Culpa repellat unde', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (86, 'Architecto i', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (87, 'A sed pariatur qua', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (88, 'Tempore assumenda aperiam', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (89, 'Sed ullam tempora iusto co', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (90, 'Ipsa', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (91, 'Fugiat incidun', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (92, 'Molestiae of', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (93, 'Quae quisquam cons', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (94, 'Repellendus ea non facil', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (95, 'Quod non quibu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (96, 'Numquam velit distinctio', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (97, 'Necessitatibus nihil ex debi', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (98, 'Velit tempore nemo, na', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (99, 'Nesciunt v', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (100, 'Dicta enim debitis accusantiu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (101, 'Vitae a', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (102, 'Praesentium voluptas u', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (103, 'Unde ullam mollitia? Nu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (104, 'Neque molestias qu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (105, 'Officiis es', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (106, 'Beatae mi', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (107, 'Mollitia nam corporis temp', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (108, 'Repudiandae repellat i', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (109, 'Laboriosam', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (110, 'Nam minus amet', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (111, 'Harum quae volup', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (112, 'Impedit facere ulla', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (113, 'Enim', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (114, 'Dolore magni', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (115, 'Eaque at corpori', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (116, 'Fug', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (117, 'Dolorum laudanti', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (118, 'Perferendis nat', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (119, 'Cupidi', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (120, 'Commodi eius dicta digniss', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (121, 'Debitis eu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (122, 'Nihil repella', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (123, 'Rem quasi minima hic sed anim', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (124, 'Sed ali', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (125, 'Earum vol', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (126, 'Inventore tempore com', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (127, 'Repell', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (128, 'Consequatur quis recusandae qu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (129, 'Dolores ea velit mi', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (130, 'Atque blanditiis a aperiam', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (131, 'Reprehenderit sequi iu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (132, 'Natus architecto eos, hic blan', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (133, 'Ipsa illo quas', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (134, 'Voluptas ali', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (135, 'Voluptates obcaecati quod e', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (136, 'Dolor adipisci a voluptate', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (137, 'Repellendus natus quae, n', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (138, 'Laudantium earum nam in dol', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (139, 'Molestias face', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (140, 'Maiores suscipit exc', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (141, 'Illum dolore perferen', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (142, 'Explicabo recusandae ma', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (143, 'Odio obcaecati hic nostrum n', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (144, 'Voluptate ali', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (145, 'Repudiandae vitae sapiente mol', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (146, 'Ipsam cumque', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (147, 'Fugiat quos alias eos dese', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (148, 'Eaque impe', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (149, 'Elige', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (150, 'Adip', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (151, 'Fuga nemo vel mo', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (152, 'Libero cumque impedit eveniet', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (153, 'Odio soluta', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (154, 'Vero nostrum duc', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (155, 'Repellend', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (156, 'Quod', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (157, 'Suscipit reiciend', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (158, 'Voluptat', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (159, 'Porro dolor fuga quam', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (160, 'Amet quo fugit aliquam sequi', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (161, 'Magni adipisci veritatis sit q', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (162, 'Debitis enim cumque cum qu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (163, 'Dolorem eligend', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (164, 'Autem lib', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (165, 'Saepe assumenda perferendis f', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (166, 'Deserunt', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (167, 'Provident soluta simil', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (168, 'In accu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (169, 'Inve', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (170, 'Placeat sapiente', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (171, 'Ducimus architecto ullam', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (172, 'Voluptate tempora rerum', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (173, 'Totam incidunt earum perspicia', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (174, 'Optio quas e', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (175, 'Ab illum invento', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (176, 'Repellat quis natus totam, s', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (177, 'Est voluptate accusantium tem', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (178, 'Beatae q', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (179, 'Velit', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (180, 'Minus nequ', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (181, 'Autem eos voluptates off', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (182, 'Vel fug', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (183, 'Architecto repudian', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (184, 'Opti', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (185, 'Iust', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (186, 'Sapiente', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (187, 'Officiis repellat corrupti su', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (188, 'Dicta et natus e', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (189, 'At quos', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (190, 'Laborum ven', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (191, 'Exceptur', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (192, 'Reiciendis assumenda dolo', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (193, 'Poss', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (194, 'Acc', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (195, 'Placeat esse archit', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (196, 'Enim repellendus nihil est te', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (197, 'Ipsam incidunt t', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (198, 'Iure', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (199, 'Illo en', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (200, 'A rem ex', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (201, 'Officiis su', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (202, 'Numquam molestias', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (203, 'Voluptates unde', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (204, 'Quae praesentium vel', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (205, 'Quas', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (206, 'Dolores aliquid inv', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (207, 'Mollitia tempore laborum eaqu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (208, 'Nobis voluptates fugiat quia', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (209, 'Similique dolorem dolore maio', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (210, 'Sapiente', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (211, 'Officia nisi dolore', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (212, 'Distinctio', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (213, 'Eos quia dignissimos saepe vel', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (214, 'Ullam neque sint eligendi', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (215, 'Excepturi deleniti ab a', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (216, 'Accusa', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (217, 'Reiciendis laboriosam di', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (218, 'Delectus ex', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (219, 'Pari', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (220, 'Veritatis velit facilis iste', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (221, 'Dol', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (222, 'Qui iste pr', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (223, 'Deleni', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (224, 'Reprehenderit volu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (225, 'Accusantium vitae n', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (226, 'Natus consequatur incidun', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (227, 'Dignissimos a', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (228, 'Vitae modi', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (229, 'Accusantium qu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (230, 'Reiciendis dignissimos ratio', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (231, 'Expedita provident natus volup', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (232, 'Rerum repellat voluptas c', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (233, 'Maiores quos incidunt dolor', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (234, 'Aper', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (235, 'Nulla', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (236, 'Laudantium tempora itaque', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (237, 'Reprehenderit', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (238, 'Aliqu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (239, 'Odio harum nam mole', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (240, 'Arc', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (241, 'Reprehenderit li', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (242, 'Repr', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (243, 'Optio m', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (244, 'Esse odit amet rep', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (245, 'Provident nostrum minima', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (246, 'Ex nihil quae facilis a omni', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (247, 'Dolorem quaerat sunt', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (248, 'Distinctio', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (249, 'Repudiandae ip', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (250, 'Iste debitis dolorum amet m', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (251, 'Non qui vo', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (252, 'Dolorem ma', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (253, 'Molestias labore tempore ita', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (254, 'Vol', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (255, 'Adipisci molest', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (256, 'Omni', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (257, 'Voluptatibus dolor', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (258, 'Quo', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (259, 'Atque aspernatur possi', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (260, 'Ullam c', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (261, 'Iusto quas voluptatibu', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (262, 'Optio qui sunt dolores, ab', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (263, 'Illum recusandae nulla re', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (264, 'Verita', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (265, 'Expedita quod blanditiis', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (266, 'Mag', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (267, 'Omnis quos aspernatur d', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (268, 'Sunt impedit co', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (269, 'Minima quam ea ad', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (270, 'Suscipit quidem e', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (271, 'Harum', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (272, 'Dolore laborum ips', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (273, 'Magni veniam earum corporis', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (274, 'Optio', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (275, 'Nam fugit vel.', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (276, 'Ut numquam quam eum, alias ius', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (277, 'Error amet tempore nulla', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (278, 'Deserunt a', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (279, 'Aperiam sit', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (280, 'Asperi', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (281, 'Similique aperiam earum expli', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (282, 'Iure h', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (283, 'At sint ducimus nostrum i', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (284, 'Reprehenderit temporib', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (285, 'Molestiae quaerat maxim', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (286, 'Maior', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (287, 'Unde natus ut ipsa cupi', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (288, 'Praesentium atque ear', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (289, 'Rem minima', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (290, 'Provident sed soluta, sed si', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (291, 'Natus quia veritatis', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (292, 'Vero a', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (293, 'Optio harum labori', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (294, 'Duci', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (295, 'Ipsa elige', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (296, 'Sunt blanditiis i', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (297, 'Doloremque', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (298, 'Autem ratione vitae quos, do', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (299, 'Voluptatibus aliquid', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (300, 'Quaerat sequi sit eius corpori', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (301, 'Libe', 0, 0, 10, 1, 1, 1, 1);
INSERT INTO charactercreator_character(character_id, name, level, exp, hp, strength, intelligence, dexterity, wisdom) VALUES (302, 'Aliquam n', 0, 0, 10, 1, 1, 1, 1);
