# -*- coding: utf-8 -*-
"""DS6_Postgres_Demo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ytC02TuG4VnHKTLJ2F7L1TvE2cwWYXL2

**POSTGRES DEMO**
"""

import psycopg2
import wget
import sqlite3

dbname = 'vvgcyvfu'
user = 'vvgcyvfu'
password = 'ClEpNjrjIHh5TUmd11b_XYLJb35tzMuj'
host = 'salt.db.elephantsql.com'

pg_conn = psycopg2.connect(dbname = dbname, user = user, password = password, host = host )

pg_conn

pg_curs = pg_conn.cursor()

pg_curs

pg_curs.execute('SELECT * FROM users;')
print(pg_curs.fetchall())
rpg_db = wget.download('https://github.com/LambdaSchool/DS-Unit-3-Sprint-2-SQL-and-Databases/blob/master/module1-introduction-to-sql/rpg_db.sqlite3?raw=true')

print(rpg_db)
sl_conn = sqlite3.connect(rpg_db)

sl_curs = sl_conn.cursor()

count = sl_curs.execute('SELECT COUNT(*) FROM charactercreator_character;').fetchall()

count

characters = sl_curs.execute('SELECT * from charactercreator_character;').fetchall()

characters

characters[0]

characters[-1]

len(characters)

create_character_table = '''
CREATE TABLE charactercreator_character (
  character_id SERIAL PRIMARY KEY,
  name VARCHAR(30),
  level INT,
  exp INT,
  hp INT,
  strength INT,
  intelligence INT,
  dexterity INT,
  wisdom INT
);
'''

pg_curs.execute(create_character_table)

show_tables = '''
SELECT *
FROM pg_catalog.pg_tables
WHERE schemaname != 'pg_catalog'
AND schemaname != 'information_schema';
'''

pg_curs.execute(show_tables)
pg_curs.fetchall()

characters[0]

str(characters[0][1:])

example_insert = '''
INSERT INTO charactercreator_character
(name, level, exp, hp, strength, intelligence, dexterity, wisdom)
VALUES ''' + str(characters[0][1:])

print(example_insert)


for character in characters:
  insert_character = """
    INSERT INTO charactercreator_character
    (name, level, exp, hp, strength, intelligence, dexterity, wisdom)
    VALUES """ + str(character[1:]) + ';'
  # print(insert_character)
  pg_curs.execute(insert_character)

pg_curs.close()
pg_conn.commit()

pg_curs = pg_conn.cursor()  # Make a new cursor
pg_curs.execute('SELECT * FROM charactercreator_character;')
pg_characters = pg_curs.fetchall()
print(pg_characters)