# -*- coding: utf-8 -*-
"""demo_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lSfvD1IlUNgXLV0avY68nh4kyF9IkrDo
"""

import sqlite3

# create connection and sqlite3 file
conn = sqlite3.connect('demo_data.sqlite3')

# create cursor for execution
c = conn.cursor()

# create demo table
c.execute("""
CREATE TABLE data
(s text, x integer, y integer)
""")

# insert values into table
c.execute("""
INSERT INTO data VALUES ('g', 3, 9);
""")
c.execute("""
INSERT INTO data VALUES ('v', 5, 7);
""")
c.execute("""
INSERT INTO data VALUES ('f', 8, 7);
""")

# commit changes
conn.commit()

"""QUERIES"""
# number of rows
c.execute('SELECT COUNT(*) FROM data')
print(c.fetchone())

# x and y at least 5
c.execute(
    """SELECT COUNT(*) FROM data
        WHERE x > 5
        AND y > 5""")
print(c.fetchone())

c.execute(
    """SELECT DISTINCT COUNT(y) FROM data""")
print(c.fetchall())

