# -*- coding: utf-8 -*-
"""northwind.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pz5SjY4q9Q7y66EXXSYpW1vcGwg9Rycu
"""

import sqlite3

# connect to northwind
PATH = '/content/northwind_small.sqlite3'
conn = sqlite3.connect(PATH)

# creating cursor
curs = conn.cursor()

# provided from SC
curs.execute("""SELECT name FROM sqlite_master 
WHERE type='table' 
ORDER BY
name;""").fetchall()
[('Category',), ('Customer',), ('CustomerCustomerDemo',),
('CustomerDemographic',), ('Employee',), ('EmployeeTerritory',), ('Order',),
('OrderDetail',), ('Product',), ('Region',), ('Shipper',), ('Supplier',),
('Territory',)]

# Products 10 most expensive products
# Only Products table has list of items in DB
curs.execute("""
SELECT ProductName, UnitPrice 
FROM Product
ORDER BY UnitPrice DESC
LIMIT 10
""")
curs.fetchall()

# Average Age of Employee
# Hire Date - Birth Date 
# Using Employees Table
curs.execute("""
SELECT AVG(HireDate - BirthDate)
FROM Employee
""")
curs.fetchone()

