# -*- coding: utf-8 -*-
"""DS9 MongoDB

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JgC1XK7BN9HSE2SvnBLCNYIUksHvZypQ
"""

!curl ipecho.net/plain

"""username = admin
password = lnJmSZg8Wz394nlf
"""

!pip install pymongo

import pymongo

client = pymongo.MongoClient("mongodb://admin:lnJmSZg8Wz394nlf@cluster0-shard-00-00-0sjjr.mongodb.net:27017,cluster0-shard-00-01-0sjjr.mongodb.net:27017,cluster0-shard-00-02-0sjjr.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true&w=majority")
db = client.test

help(db)

client.nodes

dir(db.test)

# Insert a document
db.test.insert_one({'x':1})

# Count how mant documents
db.test.count_documents({'x':1})

# Looking for documennt
db.test.find({'x':1})

curs = db.test.find({'x':1})

dir(curs)

list(curs)

stephanie_doc = {
    'favorite animal' : 'alpaca',
    'favorite color' : 'blue'
}

zoli_michelle_doc = {
    'favorite animals' : ['Black Panther', 'Unicorn']
}
dorothy_doc = {
    'favorite animal':'dog'
}

db.test.insert_many([stephanie_doc,zoli_michelle_doc,dorothy_doc])

# Look at all documents
list(db.test.find())

# make more docs
more_docs = []
for i in range(10):
  doc = {'even': i % 2 == 0}
  doc['value'] = i
  more_docs.append(doc)

more_docs

db.test.insert_many(more_docs)

list(db.test.find({'even':False}))

db.test.update_one({'value':3},
                   {'$inc': {'value':5}})

list(db.test.find())

db.test.update_many({'even': True},
                    {'$inc': {'value' : 100}})

list(db.test.find())

db.test.delete_many({'even': False})

list(db.test.find())

rpg_character = (1, "King Bob", 10, 3, 0, 0, 0)

#This is how to cast dictionary
db.test.insert_one({'rpg_character': rpg_character})

db.test.insert_one({
    'sql_id': rpg_character[0],
    'name': rpg_character[1],
    'hp': rpg_character[2],
    'level': rpg_character[3]
})

list(db.test.find())





