# -*- coding: utf-8 -*-
"""Mongo.Atlas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S0ktrjZwlKnukm0FbBZDyiNbFSy9au87
"""

#find ip address
!curl ipecho.net/plain

import sys
print(sys.version)

!pip install pymongo
import pymongo

client = pymongo.MongoClient("mongodb://admin:asdfghjkl@cluster0-shard-00-00-uglnr.mongodb.net:27017,cluster0-shard-00-01-uglnr.mongodb.net:27017,cluster0-shard-00-02-uglnr.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true&w=majority")
db = client.test

db

dir(db.test)

help(db.test.insert_one)

anthony_doc = {
    'favorite_animal': 'dog'
}

rudy_doc = {
  'favorite_animal': 'cat'
}

nick_doc = {
    'favorite_animal': 'Pangolin'
}

db.test.insert_many([anthony_doc, rudy_doc, nick_doc])

list(db.test.find())

more_docs = []
for i in range(10):
  doc = {'even': i%2 == 0}
  doc['value'] = i
  more_docs.append(doc)

more_docs

db.test.insert(more_docs)

list(db.test.find({'favorite_animal': 'Pangolin'}))

db.test.update_one({'value':3},{'$inc': {'value':5}})

db.test.update_many({'even':True},{'$inc':{'value':100}})

list(db.test.find({'even':True}))

rpg_character = (1,"King Bob", 10, 3, 2, 1)
db.test.insert_one({'rpg_character': rpg_character})

ip address