# -*- coding: utf-8 -*-
"""LS DS3 MongoDB Playground.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ea-AiDGqrQ_pwoTraM7NjwcihpcVowuh

# MongoDB with PyMongo

LSDS Unit 3 Sprint 2 Module 3

Some resources:

https://docs.atlas.mongodb.com/getting-started/

https://api.mongodb.com/python/current/

HN Discussion on MongoDB versus PostgreSQL/SQLite: https://news.ycombinator.com/item?id=19158854
"""

!curl ipecho.net/plain

!pip install pymongo

import pymongo

#3.6
client = pymongo.MongoClient('mongodb+srv://jeffrowe:J30ETb&#82Zh@cluster0-am79c.mongodb.net/test?retryWrites=true&w=majority')
db = client.test

#3.4
client = pymongo.MongoClient('mongodb://jeffrowe:J30ETb&#82Zh@cluster0-shard-00-00-am79c.mongodb.net:27017,cluster0-shard-00-01-am79c.mongodb.net:27017,cluster0-shard-00-02-am79c.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true&w=majority')
db = client.test

db

client.nodes

db.test.count_documents({'y':1})

db.test.insert_one({'y':1})

db.test.count_documents({'y':1})

wills_fav = {'favorite animal':'goose'}
tomas_fav = {'favorite animal':'unicorn'}
db.test.insert_many([wills_fav,tomas_fav])

rpg_character = (1,'King Bobby B', 10, 3, 100, 0, 0, 3,5)

db.test.insert_one({
    'sql_id': 1,
    'name': rpg_character[1],
    'level': rpg_character[2],
    'exp': rpg_character[3],
    'hp': rpg_character[4],
    'strength': rpg_character[5],
    'intelligence': rpg_character[6],
    'dexterity': rpg_character[7],
    'wisdom': rpg_character[8]
    
})

list(db.test.find({'hp': 100}))

import sqlite3

conn = sqlite3.connect('rpg_db.sqlite3')

curs = conn.cursor()

values = curs.execute('select * from charactercreator_character').fetchall()

keys = ['sql_id','name','level','exp','hp','strength','intelligence','dexterity','wisdom']
dictionary =[]
for entry in values:
  dictionary.append(dict(zip(keys, entry)))

db.test.insert_many(dictionary)

dir(db.test)

db.test.count()

