"""
mango has simpler commands to execute. However using SQl allows for more
complicated query execution.

"""




"""Copy of DS9_MongoDB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/171ivrJZqDfG8-xQ7DF5PxpKIdXUJOwxW

ip: dont share with public

username: admin

password: kIiLjnHdxnppUmuY
"""

import pymongo

client = pymongo.MongoClient("insert mango unique url")
db = client.test

help(db)

client.nodes

dir(db.test)

help(db.test.insert_one)

#insert a document
db.test.insert_one({'x':1})

#count how many documents
db.test.count_documents({'x':1})

#looking for a document
db.test.find({'x':1})

curs = db.test.find({'x':1})

dir(curs)

list(curs)

stephanie_doc = {
    'favorite animal': 'alpaca',
    'favorite color': 'blue'
}

zoli_michelle_doc = {
    'favorite animal': ['Black Panther', 'Unicorn']
}

dorothy_doc = {
    'favorite animal': 'dog'
}

db.test.insert_many([stephanie_doc, zoli_michelle_doc, dorothy_doc])

#LOOK AT ALL DOCUMENTS
list(db.test.find())

#make more docs
more_docs = []
for i in range(10):
  doc = {'even': i % 2 == 0}
  doc['value'] = i 
  more_docs.append(doc)

more_docs

db.test.insert_many(more_docs)

list(db.test.find({'even':False}))

db.test.update_one({'value':3},
                   {'$inc': {'value':5}})

list(db.test.find())

db.test.update_many({'even':True},
                    {'$inc': {'value':100}})

list(db.test.find())

db.test.delete_many({'even':False})

list(db.test.find())

rpg_character = (1, "King Bob", 10, 3, 0, 0, 0)
#you would get error if you did db.test.insert_one(rpg_character)

#here is how to cast to dictionary
db.test.insert_one({'rpg_character': rpg_character})

db.test.insert_one({
    'sql_id': rpg_character[0],
    'name': rpg_character[1],
    'hp': rpg_character[2],
    'level': rpg_character[3]
})

list(db.test.find())