# -*- coding: utf-8 -*-
"""Mongo DB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xOslN0aZf1PhLV8ql6J3lqZFIzwiNooz
"""

!curl ipecho.net/plain

import pymongo

# user = admin
# pass = 7OoShySWnHyxGowY

client = pymongo.MongoClient("mongodb://admin:7OoShySWnHyxGowY@ds8-shard-00-00-ya1q2.mongodb.net:27017,ds8-shard-00-01-ya1q2.mongodb.net:27017,ds8-shard-00-02-ya1q2.mongodb.net:27017/test?ssl=true&replicaSet=DS8-shard-0&authSource=admin&retryWrites=true&w=majority")
db = client.test

db

client.nodes

# Insert a doc
db.test.insert_one({'x':1})

# DO the count again
db.test.count_documents({'x':1})

db.test.find_one({'x':1})

db.test.find({'x':1})

curs = db.test.find({'x':1})

sam_doc = {
    'favorite animal': ['Kokopo', 'Dog']
}

rosie_doc = {
    'favorite animal': 'Snakes',
    'favorite color': 'Cyan'
}

amer_doc = {
    'favorite animal': 'Red Panda'
}

db.test.insert_many([sam_doc, rosie_doc, amer_doc])

list(db.test.find())

# Lets make more documents
more_doc = []
for i in range(10):
  doc = {'even': i % 2 == 0}
  doc['value'] = i
  more_doc.append(doc)

more_doc

# Insert the docs from above
db.test.insert_many(more_doc)

list(db.test.find({'even': False}))

list(db.test.find({'favorite animal': 'Red Panda'}))

help(db.test.update_one)

db.test.update_one({'value':3},
                   {'$inc': {'value':5}})

list(db.test.find())

db.test.update_many({'even':True},
                    {'$inc': {'value':100}})

list(db.test.find({'even': True}))

db.test.delete_many({'even': False})

list(db.test.find())

rpg_character = (1, 'King Bob', 10, 3, 0, 0, 0)

#Wrap this in a simple dicitonary so the the insert_one method works
db.test.insert_one({'rpg_character': rpg_character})

list(db.test.find())

db.test.insert_one({
    'sql_id': rpg_character[0],
    'name': rpg_character[1],
    'hp': rpg_character[2],
    'level': rpg_character[3]
})

