# -*- coding: utf-8 -*-
"""MongoDB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17nWrYP7sCwWnvvsUyKRFrQUPuHGIxRrg
"""

!curl https://ipecho.net/plain
import pymongo
client = pymongo.MongoClient("mongodb://admin:<!Bond0017>@cluster0-shard-00-00-u8tbj.mongodb.net:27017,cluster0-shard-00-01-u8tbj.mongodb.net:27017,cluster0-shard-00-02-u8tbj.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true&w=majority")
db = client['rpg']['rpg']

import sqlite3
conn_sl = sqlite3.connect('rpg_db.sqlite3')
curs_sl = conn_sl.cursor()

query = '''
SELECT name 
FROM sqlite_master
WHERE type='table' 
AND name NOT LIKE 'sqlite_%';
'''
table_names = curs_sl.execute(query).fetchall()

db

import pandas as pd
mongo_query = {}
for i in table_names:
  df = pd.read_sql_query(f'SELECT * FROM {i[0]}', conn_sl)
  db.insert_many(df.to_dict('records'))

df.to_dict('records')

query = '''
SELECT item_id, name, value, weight
FROM armory_item; 
'''
curs_sl.execute(query).fetchall()

