# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B0Hk9sN5TLcZCWHrUBkhcqVRACEbEYRE
"""

pip install psycopg2-binary

import psycopg2

dbname = 'user' #same than user
user = 'user' #same than dbname
password = 'pass' #Don't commit this to github
host = 'host' #from SERVER type

pg_conn = psycopg2.connect(dbname=dbname, user=user, password=password, host=host)

pg_conn

pg_curs = pg_conn.cursor()

create_passengers_table = """
  CREATE TABLE passengers (  
    id SERIAL NOT NULL PRIMARY KEY, 
    survived INT,
    pclass INT,
    name VARCHAR(255),
    sex VARCHAR(255),
    age INT,
    siblings_spouses INT,
    parents_children INT,
    fare NUMERIC
);
"""

pg_curs.execute(create_passengers_table)

show_tables = """
SELECT *
FROM pg_catalog.pg_tables
WHERE schemaname != 'pg_catalog'
AND schemaname != 'information_schema';
"""

pg_curs.execute(show_tables)

pg_curs.fetchall()

import csv
csv_data = csv.reader('https://raw.githubusercontent.com/VeraMendes/DS-Unit-3-Sprint-2-SQL-and-Databases/master/module2-sql-for-analysis/titanic.csv')

csv_data

csv_data = pd.read_csv('https://raw.githubusercontent.com/VeraMendes/DS-Unit-3-Sprint-2-SQL-and-Databases/master/module2-sql-for-analysis/titanic.csv')

csv_data = csv_data.rename({'Survived': 'survived', 'Pclass': 'pclass', 'Sex': 'sex', 'Age': 'age', 'Siblings/Spouses Aboard': 'siblings_spouses', 'Parents/Children Aboard': 'parents_children', 'Fare': 'fare'}, axis='columns')

csv_data

f = open(r'C:\lambda\unit3_2\DS-Unit-3-Sprint-2-SQL-and-Databases\module2-sql-for-analysis\titanic.csv','r')
pg_curs.copy_from(f, passengers, sep=',')
f.close()

pg_curs.copy_from(r'C:\lambda\unit3_2\DS-Unit-3-Sprint-2-SQL-and-Databases\module2-sql-for-analysis\titanic.csv', 'passengers')

example_insert = """
INSERT INTO passenger
(survived, pclass, name, sex, siblings_spouses, parents_children, fare)
VALUES """ + str(csv_data[0][1:]) + ';'

print(example_insert)

pg_curs.close()
pg_conn.commit()

\copy passengers (survived, pclass, name, sex, age, siblings_spouses, parents_children, fare) from 'C:/lambda/unit3_2/DS-Unit-3-Sprint-2-SQL-and-Databases/module2-sql-for-analysis/titanic.csv' CSV HEADER;