# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B0Hk9sN5TLcZCWHrUBkhcqVRACEbEYRE
"""

import psycopg2
import csv
import pandas as pd

dbname = 'user' #same than user
user = 'user' #same than dbname
password = 'pass' #Don't commit this to github
host = 'host' #from SERVER type

pg_conn = psycopg2.connect(dbname=dbname, user=user, password=password, host=host)
pg_conn

pg_curs = pg_conn.cursor()

create_passengers_table = """
  CREATE TABLE passengers (  
    id SERIAL NOT NULL PRIMARY KEY, 
    survived INT,
    pclass INT,
    name VARCHAR(200),
    sex VARCHAR(20),
    age INT,
    siblings_spouses INT,
    parents_children INT,
    fare NUMERIC(30)
);
"""

pg_curs.execute(create_passengers_table)

show_tables = """
SELECT *
FROM pg_catalog.pg_tables
WHERE schemaname != 'pg_catalog'
AND schemaname != 'information_schema';
"""

pg_curs.execute(show_tables)
pg_curs.fetchall()

csv_data = pd.read_csv('titanic.csv')

# Input each row from the DataFrame into the Database
    statement = """
        INSERT INTO passengers (
            survived, 
            pclass, 
            name, 
            sex, 
            age, 
            siblings_spouses, 
            parents_children, 
            fare 
        ) VALUES
        (%s, %s, %s, %s, %s, %s, %s, %s);
        """

data = [row for row in csv_data.itertuples(index=False)]

for item in data:
  pg_curs.execute(
  statement, 
  item
  )

pg_curs.close()
pg_conn.commit()