# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1srt1cemHGQdVTAoEjc7hGVpxRaXipS_A
"""

!pip install psycopg2-binary

import pandas as pd
import psycopg2
dir(psycopg2)

dbname = 'TODO'
user = 'TODO'
password = 'TODO'
host = 'TODO'

pg_conn = psycopg2.connect(dbname=dbname, user=user, password=password, host=host)

pg_conn

pg_curs = pg_conn.cursor()

!wget https://raw.githubusercontent.com/AndrewSLowe/DS-Unit-3-Sprint-2-SQL-and-Databases/master/module2-sql-for-analysis/titanic.csv

import sqlite3

# create types for two of the titanic data columns to limit input
create_pclass = "CREATE TYPE pclass as ENUM ('1','2','3');"

pg_curs.execute(create_pclass)

pg_curs.execute("CREATE TYPE gender AS ENUM ('male', 'female', 'other');")

# create empty passenger table to be exported into postgres later
create_passenger_table = """
create table passengers (
passenger_id serial primary key,
survived boolean,
pclass INT,
name varchar(100),
sex gender,
age int,
sibling_spouse_aboard int,
parents_children_aboard int,
fare float);
"""


pg_curs.execute(create_passenger_table)

infile = 'titanic.csv'
df = pd.read_csv(infile)

# pclass is a type created above defined to be strings, so it must be changed in the dataframe for consistancy.
# Similarly, the booleans: "Survived", "Siblings..." and "Parents..." are changed to strings because that's how postgres takes booleans. Age is an int

# df.Pclass = df.Pclass.astype(str)
# df.Survived = df.Survived.astype(str)
# df.Age = df.Age.astype(int)

df = pd.read_csv('titanic.csv')
df['Survived'] = df['Survived'].astype(bool)

df = df.replace("'", '"', regex=True)

for i in range(len(df)):
    row = df.loc[i]
    insert_row = """
        INSERT INTO passengers
        (survived, pclass, name, sex, age, sibling_spouse_aboard, parents_children_aboard, fare)
        VALUES """ + str(tuple(row)) + ';'
    pg_curs.execute(insert_row)

pg_curs.close()
pg_conn.commit()
