# -*- coding: utf-8 -*-
"""DS7 sql 10-8-2019.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jOpgd-Sflk9UJCogsxFZscLSMjbGNRRX
"""

!pip install psycopg2-binary

import psycopg2

dir(psycopg2)

#Create connection
dbname = 'mtjkhpkq'
user = 'mtjkhpkq'
password = 'x7M6MekGN5kaGkX4lW0szHUvX9acs7Yw' 
host = 'salt.db.elephantsql.com'

conn = psycopg2.connect(dbname = dbname, user = user, password = password, host = host)

#delete connection
del conn

pg_conn = psycopg2.connect(dbname = dbname, user = user, password = password, host = host)

#cursor... what is a cursor?
pg_curs = pg_conn.cursor()

pg_curs.execute('SELECT * FROM TEST_TABLE;')

pg_curs.fetchall()

!wget https://github.com/LambdaSchool/DS-Unit-3-Sprint-2-SQL-and-Databases/blob/master/module1-introduction-to-sql/rpg_db.sqlite3?raw=true

!ls -alh

!mv 'rpg_db.sqlite3?raw=true' rpg_db.sqlite3

import sqlite3

sl_conn = sqlite3.connect('rpg_db.sqlite3')

sl_curs = sl_conn.cursor()

sl_curs.execute('SELECT COUNT(*) FROM charactercreator_character').fetchall()

sl_curs.execute('SELECT COUNT(DISTINCT name) FROM charactercreator_character;').fetchall()

characters = sl_curs.execute('SELECT * FROM charactercreator_character;')

# characters[0]

#look at last one
# characters[-1]

# len(characters)

sl_curs.execute('PRAGMA table_info(charactercreator_character);').fetchall()

create_character_table = """
CREATE TABLE charactercreator_character (
  character_id SERIAL PRIMARY KEY,
  name VARCHAR(30),
  level INT,
  exp INT,
  hp INT,
  strength INT,
  intellegence INT,
  dexterity INT,
  wisdom INT
  );
"""

pg_curs.execute(create_character_table)

show_tables = """
SELECT *
FROM pg_catalog.pg_tables
WHERE SCHEMANAME != 'pg_catalog'
AND schemaname != 'information_schema';
"""

pg_curs.execute(show_tables)

pg_curs.fetchall()

# str(characters[0][1:])

# example_insert = """
# INSERT INTO charactercreator_character
# (name, level, exp, hp, strength, intelligence, dexterity, widsdom)
# VALUES """ + str(characters[0][1:]) + ';'

# print(example_insert)

for character in characters:
  insert_character = """
    INSERT INTO charactercreator_character
    (name, level, exp, hp strength, intellgience, dexterity, wisdom)
    VALUES """ + str(character[1:]) + ';'
  
  print(insert_character)
  pg_curs.execute(insert_character)

pg_curs.execute('SELECT * FROM charactercreator_character;')

pg_curs.fetchall()

pg_conn.close()