# -*- coding: utf-8 -*-
"""titanic_postgres.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gKE3ZUiGkINJqMYfLTDK-6EY3tXOaTr6
"""

!pip install psycopg2-binary

import psycopg2 as psy
import sqlite3
import pandas as pd

titanic = pd.read_csv('titanic.csv')
titanic.shape

titanic.head(30)

titanic.Name = titanic.Name.str.replace("'","`")

conn = sqlite3.connect('titanic.sqlite3')
titanic.to_sql(name='titanic', con=conn, if_exists='replace')
sl_curs = conn.cursor()

human = sl_curs.execute('select * from titanic;').fetchall()

human[0]

titanic.head(1)

dbname = 'qagmppdk'
user = 'qagmppdk'
password = 'KBR_FileILZpJHxTq4XfZvkg_6BpqzGK'
host ='raja.db.elephantsql.com'

pg_conn = psy.connect(dbname=dbname,user=user,password=password,host=host)
pg_curs = pg_conn.cursor()

pg_conn

create_titanic_table = '''
CREATE TYPE gender AS ENUM ('female', 'male');
CREATE TABLE titanic (
  id SERIAL PRIMARY KEY,
  survived INT,
  pclass INT,
  name VARCHAR(100),
  sex gender,
  age INT,
  siblings_spouses_aboard INT,
  parents_children_aboard INT,
  fare FLOAT
  )'''

pg_curs.execute(create_titanic_table)

str(human[0])

attempted_insert = '''
  INSERT INTO titanic
  VALUES ''' + str(human[0])
attempted_insert

pg_curs.execute(attempted_insert)

pg_conn.commit

pg_curs = pg_conn.cursor()
pg_curs.execute('SELECT * FROM  titanic;')
pg_human = pg_curs.fetchall()

for humans in human[1:]:
  insert_humans = '''
  INSERT INTO titanic
  VALUES ''' + str(humans)
  pg_curs.execute(insert_humans)

pg_conn.commit

pg_curs = pg_conn.cursor()
pg_curs.execute('SELECT * FROM  titanic;')
pg_human = pg_curs.fetchall()

pg_human[28]

