# -*- coding: utf-8 -*-
"""Titanic SQL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BDLMBbodJmGB7BT-WzAfaUySQ-ODJdMO
"""

!pip install psycopg2-binary

import psycopg2

dbname = 'pephijyl'
user = 'pephijyl'
password = 'IJ7uyPoay_6F2CxtPWwRbWFC9h78aIIi' # Don't commit this 
host = 'raja.db.elephantsql.com'
pg_conn = psycopg2.connect(dbname=dbname, user=user,
                           password=password, host=host)

pg_curs = pg_conn.cursor()

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/mkirby1995/DS-Unit-3-Sprint-2-SQL-and-Databases/master/module2-sql-for-analysis/titanic.csv')
df.info()

len(df['Fare'].value_counts())

create_titanic_table = """
CREATE TABLE titanic (
  name SERIAL PRIMARY KEY,
  survived NUMERIC(2),
  class NUMERIC(3),
  sex NUMERIC(2),
  age SMALLINT,
  sibling_spouse_aboard SMALLINT,
  children_parents_aboard SMALLINT,
  fare SMALLINT)"""

#pg_curs.execute(create_titanic_table)
#pg_conn.commit()

df = df.rename(columns={'Siblings/Spouses Aboard':'sibling_spouse_aboard','Parents/Children Aboard':'children_parents_aboard'})

df.to_sql(name='titanic',
          con = pg_conn,
          if_exists='replace',
          index=True,
          index_label='id',
          dtype={'Name':'SERIAL PRIMARY KEY',
                 'Survived':'NUMERIC(2)',
                 'Pclass':'NUMERIC(3)',
                 'Sex':'NUMERIC(2)',
                 'Age':'SMALLINT',
                 'sibling_spouse_aboard':'SMALLINT',
                 'children_parents_aboard':'SMALLINT',
                 'Fare':'SMALLINT'})
