# -*- coding: utf-8 -*-
"""Titanic SQL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BDLMBbodJmGB7BT-WzAfaUySQ-ODJdMO
"""

!pip install psycopg2

import psycopg2

dbname = 'pephijyl'
user = 'pephijyl'
password = 'IJ7uyPoay_6F2CxtPWwRbWFC9h78aIIi' # Don't commit this 
host = 'raja.db.elephantsql.com'
postgres_conn = psycopg2.connect(dbname=dbname, user=user,
                           password=password, host=host)

postgres_curs = postgres_conn.cursor()

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/mkirby1995/DS-Unit-3-Sprint-2-SQL-and-Databases/master/module2-sql-for-analysis/titanic.csv')
df.info()

df['Name']=df['Name'].str.replace('\'','')

df['Sex'] = df['Sex'].replace({'male':1,'female':0})

"""[create_engine](https://docs.sqlalchemy.org/en/13/core/engines.html)"""

import sqlite3
from sqlalchemy import create_engine
engine = create_engine('sqlite://', echo=False)

"""[df.to_sql](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DataFrame.to_sql.html)"""

df.to_sql('titanic', con=engine)

titanic_engine = engine.execute("SELECT * FROM titanic").fetchall()

"""[sqlite3 data types](https://www.sqlite.org/datatype3.html)"""

create_titanic_table = """
CREATE TABLE titanic_table (
  id SERIAL PRIMARY KEY,
  survived INT,
  pclass INT,
  name VARCHAR(200),
  sex INT,
  age INT,
  sibs_spos INT,
  par_chi INT,
  fare DECIMAL
)"""

postgres_conn = psycopg2.connect(dbname = dbname, user=user, password=password,host=host)
postgres_curs = postgres_conn.cursor()
postgres_curs.execute(create_titanic_table)

for person in titanic_engine:
  insert_person="""
  INSERT INTO titanic_table
  VALUES
  """ + str(person)
  postgres_curs.execute(insert_person)
  
postgres_conn.commit()

#postgres_curs.execute('SELECT * FROM titanic_table;')
#postgres_curs.fetchone()
