# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PWqTXGqNHVL57JwQaSwfs6ResMoEw4bD
"""

!pip install psycopg2-binary

import psycopg2 as psy

dbname = 'apyydkhz'
user = 'apyydkhz'
password = 'CLTMR3jZ2CgNb3IzHgNCusDFQaer63xO'
host ='raja.db.elephantsql.com'

pg_conn = psy.connect(dbname=dbname,user=user,password=password,host=host)

pg_conn

!wget https://github.com/LambdaSchool/DS-Unit-3-Sprint-2-SQL-and-Databases/blob/master/module1-introduction-to-sql/rpg_db.sqlite3?raw=true

!mv 'rpg_db.sqlite3?raw=true' rpg_db.sqlite3

import sqlite3
sl_conn= sqlite3.connect('rpg_db.sqlite3')
sl_curs = sl_conn.cursor()

sl_curs.execute('SELECT COUNT(*) FROM charactercreator_character;').fetchall()

characters = sl_curs.execute('SELECT * FROM charactercreator_character;').fetchall()

characters[0]

create_character_table = '''
CREATE TABLE charactercreator_character (
  character_id SERIAL PRIMARY KEY,
  name VARCHAR(30),
  level INT,
  exp INT,
  hp INT,
  strength INT,
  intelligence INT,
  dexterity INT,
  wisdom INT
)
'''

pg_curs = pg_conn.cursor()

pg_curs.execute(create_character_table)

str(characters[0])

attempted_insert = '''
  INSERT INTO charactercreator_character
  VALUES ''' + str(characters[0])
attempted_insert

pg_curs.execute(attempted_insert)

pg_conn.commit()

pg_curs = pg_conn.cursor()
pg_curs.execute('SELECT * FROM  charactercreator_character;')
pg_characters = pg_curs.fetchall()

pg_characters[0]

len(pg_characters)

for character in characters[1:]:
  insert_character = '''
  INSERT INTO charactercreator_character
  VALUES ''' + str(character)
  pg_curs.execute(insert_character)

pg_conn.commit()

pg_curs = pg_conn.cursor()
pg_curs.execute('SELECT * FROM charactercreator_character;')
pg_characters = pg_curs.fetchall()

len(pg_characters)

pg_characters[0]

pg_characters[-1]

