# -*- coding: utf-8 -*-
"""Unit_3_Module_2_Assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-tPWv6KkyoG69ymyKscQf-AtrUZifncz
"""

!pip install psycopg2-binary

import psycopg2
import os
import sqlite3
import pandas as pd

dbname = 'bwbdhntd'
user = 'bwbdhntd'
password = ''
host = 'salt.db.elephantsql.com'

!wget https://raw.githubusercontent.com/justin-hsieh/DS-Unit-3-Sprint-2-SQL-and-Databases/master/module2-sql-for-analysis/titanic.csv

df = pd.read_csv('titanic.csv')

df['Name'] = df['Name'].str.replace("'", '', regex=True)
df.head()

tit_conn = sqlite3.connect('titanic1.sqlite3')
df.to_sql('titanic1', tit_conn, index=False)

tit_curs = tit_conn.cursor()

passengers = tit_curs.execute('SELECT * FROM titanic1').fetchall()
passengers

titpg_conn = psycopg2.connect(dbname=dbname, user=user,
                           password=password, host=host)
titpg_curs = titpg_conn.cursor()

tit_curs.execute('PRAGMA table_info(titanic1);').fetchall()

create_titanic_table = '''
    CREATE TABLE titanic1 (
        Survived INT,
        Pclass INT,
        Name VARCHAR(600),
        Sex VARCHAR(100),
        Age FLOAT,
        Siblings_Spouses_Aboard INT,
        Parents_Children_Aboard INT,
        Fare FLOAT
        )
    '''

titpg_curs.execute(create_titanic_table)

example_insert = """
        INSERT INTO titanic1
        (Survived, Pclass, Name, Sex, Age, Siblings_Spouses_Aboard, 
        Parents_Children_Aboard, Fare)
        VALUES """ + str(passengers[0][1:])

print(example_insert)

for passenger in passengers:
    insert_passenger = """
        INSERT INTO titanic1
        (Survived, Pclass, Name, Sex, Age, Siblings_Spouses_Aboard, 
        Parents_Children_Aboard, Fare)
        VALUES """ + str(passenger[:]) + ';'
    titpg_curs.execute(insert_passenger)

titpg_conn.commit()
titpg_curs.close()